name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: PHP 8.3 Tests & Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer
          coverage: pcov  # Для генерации покрытия

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit
        run: composer phpunit

      - name: Run PHPStan
        run: composer phpstan

      - name: Run PHP-CS-Fixer
        run: composer php-cs-fixer-check

      - name: Upload coverage to Coveralls (optional)
        if: success() && github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls --dev
          php vendor/bin/php-coveralls -v
